[package]
name = "libmlv"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/ilia3101/LibMLV-rs"
description = "Read MLV (magic lantern video) files."
license = "GPL-3.0-only or GPL-2.0-only or MIT or Apache-2.0"
include = [
    "src/*.rs",
    "src/bin/*.rs",
    "/Cargo.toml",
    "/README.md",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rawloader = { version = "0.37.1", optional = true }
hound = { version = "3", optional = true }

[lib]
name = "mlv"

[features]
default = ["std"] # Use of standard library enabled by default
std = []
raw2mlv-deps = ["rawloader"]
audio-export = ["hound"]

[[bin]]
name = "raw2mlv"
required-features = ["raw2mlv-deps"]

[[bin]]
name = "index_demo"
required-features = []

[[bin]]
name = "speed_test"
required-features = ["raw2mlv-deps"]

[[bin]]
name = "extract_audio"
required-features = ["audio-export"]
