[package]
name = "libmlv"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/ilia3101/LibMLV-rs"
description = "Read MLV (magic lantern video) files."
license = "GPL-3.0-only or GPL-2.0-only or MIT or Apache-2.0"
include = [
    "src/*.rs",
    "src/bin/*.rs",
    "/Cargo.toml",
    "/README.md",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rawler = { version = "0.7.2", optional = true }
hound = { version = "3", optional = true }
argparse = { version = "0.2.2", optional = true }
clap = { version = "4.6.1", features = ["derive"], optional = true }
rand = { version = "0.8", optional = true }
eframe = { version = "0.29", optional = true }
rfd = { version = "0.15", optional = true }
tqdm = { version = "0.8.0", optional = true }


[build-dependencies]
cc = { version = "1", optional = true }

[lib]
name = "mlv"

[features]
default = ["std"] # Use of standard library enabled by default
std = []
raw2mlv-deps = ["dep:rawler", "dep:clap", "dep:rand", "dep:tqdm"]
audio-export = ["dep:hound"]
egui = ["dep:eframe", "dep:rfd"]
cineform = ["std", "dep:cc"]
jpeg2000 = ["std", "dep:cc"]
compress-mlv = ["cineform", "jpeg2000", "dep:clap", "dep:tqdm"]

[[bin]]
name = "raw2mlv"
required-features = ["raw2mlv-deps"]

[[bin]]
name = "index_demo"
required-features = []

[[bin]]
name = "speed_test"
required-features = ["raw2mlv-deps"]

[[bin]]
name = "compress_mlv"
required-features = ["compress-mlv"]

[[bin]]
name = "extract_audio"
required-features = ["audio-export"]

[[bin]]
name = "gui"
required-features = ["egui"]
